version: 2
jobs:
  build:
    docker:

      - image: scuevals/circleci
        environment:
          FLASK_ENV: test
          JWT_SECRET_KEY: lHmxPAbKYd4wCQctLEuJK7K5CTlQb8sP
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install_egg_info
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python setup.py test
            (coverage run --source=scuevals_api setup.py test && coverage report --fail-under=100 && coveralls)

      - run:
          name: Run documentation tests
          command: dredd

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy-staging:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "$HEROKU_APP_STAGING"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Restore Database From Production
          command: |
            if [ "$DEPLOY_STAGING_RESTORE_DB" == "1" ]; then
              heroku pg:reset DATABASE --app $HEROKU_APP_STAGING --confirm $HEROKU_APP_STAGING
              heroku pg:backups:restore `heroku pg:backups:public-url --app $HEROKU_APP_PRODUCTION` DATABASE_URL --app $HEROKU_APP_STAGING --confirm $HEROKU_APP_STAGING
            else
              echo Skipping DB restore according to env var...
            fi
      - run:
          name: Deploy to Heroku
          command: |
            heroku git:remote -a $HEROKU_APP_STAGING
            echo Pushing to Heroku...
            git push heroku develop:master &>/dev/null

  deploy-production:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "$HEROKU_APP_PRODUCTION"
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            heroku git:remote -a $HEROKU_APP_PRODUCTION
            echo Pushing to Heroku...
            git push heroku master:master &>/dev/null

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-staging:
          filters:
            branches:
              only: develop
          requires:
            - build
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - build
