#!/bin/bash

export MAIN_DB=scuevals
export TMP_DB=scuevals_new

function delete_db () {
    psql -d ${1} -c "SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.datname = '$1'
  AND pid <> pg_backend_pid();" || true

    dropdb ${1} || true
}

delete_db ${TMP_DB} &>/dev/null

echo Fetching $MAIN_DB from Heroku...

heroku pg:pull DATABASE_URL ${TMP_DB} -r production

read -p "Please confirm the replacement of the existing $MAIN_DB db? (y/n) " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo Replacing $MAIN_DB with $TMP_DB...

    delete_db ${MAIN_DB}

    psql -c "ALTER DATABASE $TMP_DB RENAME TO $MAIN_DB;"
fi