#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: compile_alembic_template alembic/versions/<file>"
    exit 1
fi

if [ "${PWD##*/}" == "scripts" ]; then
  cd ../db || exit 1
else
  cd db || exit 1
fi

cat $1 | mako-render > ${1%.*}